/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CourseManager {
  export type CourseStruct = {
    courseId: BigNumberish;
    name: string;
    description: string;
    price: BigNumberish;
    instructor: AddressLike;
    isActive: boolean;
    createdAt: BigNumberish;
    totalStudents: BigNumberish;
    contentHash: string;
    thumbnailHash: string;
  };

  export type CourseStructOutput = [
    courseId: bigint,
    name: string,
    description: string,
    price: bigint,
    instructor: string,
    isActive: boolean,
    createdAt: bigint,
    totalStudents: bigint,
    contentHash: string,
    thumbnailHash: string
  ] & {
    courseId: bigint;
    name: string;
    description: string;
    price: bigint;
    instructor: string;
    isActive: boolean;
    createdAt: bigint;
    totalStudents: bigint;
    contentHash: string;
    thumbnailHash: string;
  };
}

export interface CourseManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "courseIds"
      | "courses"
      | "createCourse"
      | "getActiveCourses"
      | "getAllCourseIds"
      | "getCourse"
      | "getCourseContent"
      | "getInstructorCourses"
      | "getTotalCourses"
      | "incrementStudentCount"
      | "instructorCourses"
      | "owner"
      | "toggleCourseStatus"
      | "transferOwnership"
      | "updateCourse"
      | "updateCourseContent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CourseContentUpdated" | "CourseCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "courseIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCourse",
    values: [string, string, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCourses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCourseIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourseContent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstructorCourses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCourses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "incrementStudentCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "instructorCourses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "toggleCourseStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCourse",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCourseContent",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "courseIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCourseIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCourse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCourseContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstructorCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementStudentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "instructorCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleCourseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCourseContent",
    data: BytesLike
  ): Result;
}

export namespace CourseContentUpdatedEvent {
  export type InputTuple = [courseId: BigNumberish, newContentHash: string];
  export type OutputTuple = [courseId: bigint, newContentHash: string];
  export interface OutputObject {
    courseId: bigint;
    newContentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseCreatedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    name: string,
    price: BigNumberish,
    instructor: AddressLike,
    contentHash: string,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    courseId: bigint,
    name: string,
    price: bigint,
    instructor: string,
    contentHash: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    courseId: bigint;
    name: string;
    price: bigint;
    instructor: string;
    contentHash: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CourseManager extends BaseContract {
  connect(runner?: ContractRunner | null): CourseManager;
  waitForDeployment(): Promise<this>;

  interface: CourseManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  courseIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  courses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        string,
        string
      ] & {
        courseId: bigint;
        name: string;
        description: string;
        price: bigint;
        instructor: string;
        isActive: boolean;
        createdAt: bigint;
        totalStudents: bigint;
        contentHash: string;
        thumbnailHash: string;
      }
    ],
    "view"
  >;

  createCourse: TypedContractMethod<
    [
      name: string,
      description: string,
      price: BigNumberish,
      contentHash: string,
      thumbnailHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  getActiveCourses: TypedContractMethod<
    [],
    [CourseManager.CourseStructOutput[]],
    "view"
  >;

  getAllCourseIds: TypedContractMethod<[], [bigint[]], "view">;

  getCourse: TypedContractMethod<
    [courseId: BigNumberish],
    [CourseManager.CourseStructOutput],
    "view"
  >;

  getCourseContent: TypedContractMethod<
    [courseId: BigNumberish],
    [[string, string] & { contentHash: string; thumbnailHash: string }],
    "view"
  >;

  getInstructorCourses: TypedContractMethod<
    [instructor: AddressLike],
    [bigint[]],
    "view"
  >;

  getTotalCourses: TypedContractMethod<[], [bigint], "view">;

  incrementStudentCount: TypedContractMethod<
    [courseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  instructorCourses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  toggleCourseStatus: TypedContractMethod<
    [courseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCourse: TypedContractMethod<
    [
      courseId: BigNumberish,
      name: string,
      description: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateCourseContent: TypedContractMethod<
    [courseId: BigNumberish, newContentHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "courseIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "courses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        string,
        string
      ] & {
        courseId: bigint;
        name: string;
        description: string;
        price: bigint;
        instructor: string;
        isActive: boolean;
        createdAt: bigint;
        totalStudents: bigint;
        contentHash: string;
        thumbnailHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCourse"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      price: BigNumberish,
      contentHash: string,
      thumbnailHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveCourses"
  ): TypedContractMethod<[], [CourseManager.CourseStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAllCourseIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCourse"
  ): TypedContractMethod<
    [courseId: BigNumberish],
    [CourseManager.CourseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCourseContent"
  ): TypedContractMethod<
    [courseId: BigNumberish],
    [[string, string] & { contentHash: string; thumbnailHash: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInstructorCourses"
  ): TypedContractMethod<[instructor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalCourses"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "incrementStudentCount"
  ): TypedContractMethod<[courseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "instructorCourses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "toggleCourseStatus"
  ): TypedContractMethod<[courseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCourse"
  ): TypedContractMethod<
    [
      courseId: BigNumberish,
      name: string,
      description: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCourseContent"
  ): TypedContractMethod<
    [courseId: BigNumberish, newContentHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CourseContentUpdated"
  ): TypedContractEvent<
    CourseContentUpdatedEvent.InputTuple,
    CourseContentUpdatedEvent.OutputTuple,
    CourseContentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CourseCreated"
  ): TypedContractEvent<
    CourseCreatedEvent.InputTuple,
    CourseCreatedEvent.OutputTuple,
    CourseCreatedEvent.OutputObject
  >;

  filters: {
    "CourseContentUpdated(uint256,string)": TypedContractEvent<
      CourseContentUpdatedEvent.InputTuple,
      CourseContentUpdatedEvent.OutputTuple,
      CourseContentUpdatedEvent.OutputObject
    >;
    CourseContentUpdated: TypedContractEvent<
      CourseContentUpdatedEvent.InputTuple,
      CourseContentUpdatedEvent.OutputTuple,
      CourseContentUpdatedEvent.OutputObject
    >;

    "CourseCreated(uint256,string,uint256,address,string,uint256)": TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;
    CourseCreated: TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;
  };
}
