/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CoursePurchase {
  export type PurchaseStruct = {
    courseId: BigNumberish;
    student: AddressLike;
    paidAmount: BigNumberish;
    purchaseTime: BigNumberish;
    isValid: boolean;
  };

  export type PurchaseStructOutput = [
    courseId: bigint,
    student: string,
    paidAmount: bigint,
    purchaseTime: bigint,
    isValid: boolean
  ] & {
    courseId: bigint;
    student: string;
    paidAmount: bigint;
    purchaseTime: bigint;
    isValid: boolean;
  };
}

export interface CoursePurchaseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accumulatedFees"
      | "courseManager"
      | "courseStudents"
      | "getCourseStudentCount"
      | "getCourseStudents"
      | "getStudentCourseIds"
      | "getStudentPurchases"
      | "hasPurchased"
      | "owner"
      | "platformFeeRate"
      | "purchaseCourse"
      | "purchaseCourseBatch"
      | "purchases"
      | "studentCourses"
      | "transferOwnership"
      | "updatePlatformFeeRate"
      | "withdrawAllFees"
      | "withdrawFees"
      | "ydToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoursePurchased"
      | "FeesWithdrawn"
      | "PlatformFeeRateUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courseManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courseStudents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourseStudentCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourseStudents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentCourseIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentPurchases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourseBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "purchases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "studentCourses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ydToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCourseStudentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCourseStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentCourseIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourseBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "studentCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ydToken", data: BytesLike): Result;
}

export namespace CoursePurchasedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    student: AddressLike,
    paidAmount: BigNumberish,
    instructorAmount: BigNumberish,
    platformFee: BigNumberish,
    purchaseTime: BigNumberish
  ];
  export type OutputTuple = [
    courseId: bigint,
    student: string,
    paidAmount: bigint,
    instructorAmount: bigint,
    platformFee: bigint,
    purchaseTime: bigint
  ];
  export interface OutputObject {
    courseId: bigint;
    student: string;
    paidAmount: bigint;
    instructorAmount: bigint;
    platformFee: bigint;
    purchaseTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoursePurchase extends BaseContract {
  connect(runner?: ContractRunner | null): CoursePurchase;
  waitForDeployment(): Promise<this>;

  interface: CoursePurchaseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accumulatedFees: TypedContractMethod<[], [bigint], "view">;

  courseManager: TypedContractMethod<[], [string], "view">;

  courseStudents: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getCourseStudentCount: TypedContractMethod<
    [courseId: BigNumberish],
    [bigint],
    "view"
  >;

  getCourseStudents: TypedContractMethod<
    [courseId: BigNumberish],
    [string[]],
    "view"
  >;

  getStudentCourseIds: TypedContractMethod<
    [student: AddressLike],
    [bigint[]],
    "view"
  >;

  getStudentPurchases: TypedContractMethod<
    [student: AddressLike],
    [CoursePurchase.PurchaseStructOutput[]],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [student: AddressLike, courseId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeRate: TypedContractMethod<[], [bigint], "view">;

  purchaseCourse: TypedContractMethod<
    [courseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  purchaseCourseBatch: TypedContractMethod<
    [courseIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  purchases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean] & {
        courseId: bigint;
        student: string;
        paidAmount: bigint;
        purchaseTime: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  studentCourses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlatformFeeRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawAllFees: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFees: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ydToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "courseManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "courseStudents"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCourseStudentCount"
  ): TypedContractMethod<[courseId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCourseStudents"
  ): TypedContractMethod<[courseId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStudentCourseIds"
  ): TypedContractMethod<[student: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getStudentPurchases"
  ): TypedContractMethod<
    [student: AddressLike],
    [CoursePurchase.PurchaseStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [student: AddressLike, courseId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseCourse"
  ): TypedContractMethod<[courseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "purchaseCourseBatch"
  ): TypedContractMethod<[courseIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "purchases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean] & {
        courseId: bigint;
        student: string;
        paidAmount: bigint;
        purchaseTime: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "studentCourses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformFeeRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawAllFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ydToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CoursePurchased"
  ): TypedContractEvent<
    CoursePurchasedEvent.InputTuple,
    CoursePurchasedEvent.OutputTuple,
    CoursePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeRateUpdated"
  ): TypedContractEvent<
    PlatformFeeRateUpdatedEvent.InputTuple,
    PlatformFeeRateUpdatedEvent.OutputTuple,
    PlatformFeeRateUpdatedEvent.OutputObject
  >;

  filters: {
    "CoursePurchased(uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;
    CoursePurchased: TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "PlatformFeeRateUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeRateUpdatedEvent.InputTuple,
      PlatformFeeRateUpdatedEvent.OutputTuple,
      PlatformFeeRateUpdatedEvent.OutputObject
    >;
    PlatformFeeRateUpdated: TypedContractEvent<
      PlatformFeeRateUpdatedEvent.InputTuple,
      PlatformFeeRateUpdatedEvent.OutputTuple,
      PlatformFeeRateUpdatedEvent.OutputObject
    >;
  };
}
