/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace InstructorYieldManager {
  export type InstructorYieldStruct = {
    instructor: AddressLike;
    totalYdDeposited: BigNumberish;
    totalUsdtSupplied: BigNumberish;
    lastUpdateTime: BigNumberish;
    isActive: boolean;
  };

  export type InstructorYieldStructOutput = [
    instructor: string,
    totalYdDeposited: bigint,
    totalUsdtSupplied: bigint,
    lastUpdateTime: bigint,
    isActive: boolean
  ] & {
    instructor: string;
    totalYdDeposited: bigint;
    totalUsdtSupplied: bigint;
    lastUpdateTime: bigint;
    isActive: boolean;
  };
}

export interface InstructorYieldManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aavePool"
      | "activeInstructors"
      | "depositAndInvest"
      | "emergencyWithdraw"
      | "getActiveInstructors"
      | "getInstructorAaveData"
      | "getInstructorYield"
      | "instructorYields"
      | "owner"
      | "renounceOwnership"
      | "setAavePool"
      | "setUniswapRouter"
      | "transferOwnership"
      | "uniswapRouter"
      | "usdtToken"
      | "ydToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EthSwappedToUsdt"
      | "OwnershipTransferred"
      | "UsdtSuppliedToAave"
      | "WithdrawnFromAave"
      | "YdDeposited"
      | "YdSwappedToEth"
      | "YieldProcessed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "aavePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activeInstructors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndInvest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveInstructors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInstructorAaveData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstructorYield",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "instructorYields",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAavePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUniswapRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "ydToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeInstructors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndInvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveInstructors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstructorAaveData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstructorYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "instructorYields",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAavePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ydToken", data: BytesLike): Result;
}

export namespace EthSwappedToUsdtEvent {
  export type InputTuple = [
    instructor: AddressLike,
    ethAmount: BigNumberish,
    usdtAmount: BigNumberish
  ];
  export type OutputTuple = [
    instructor: string,
    ethAmount: bigint,
    usdtAmount: bigint
  ];
  export interface OutputObject {
    instructor: string;
    ethAmount: bigint;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsdtSuppliedToAaveEvent {
  export type InputTuple = [instructor: AddressLike, usdtAmount: BigNumberish];
  export type OutputTuple = [instructor: string, usdtAmount: bigint];
  export interface OutputObject {
    instructor: string;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnFromAaveEvent {
  export type InputTuple = [instructor: AddressLike, usdtAmount: BigNumberish];
  export type OutputTuple = [instructor: string, usdtAmount: bigint];
  export interface OutputObject {
    instructor: string;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YdDepositedEvent {
  export type InputTuple = [instructor: AddressLike, ydAmount: BigNumberish];
  export type OutputTuple = [instructor: string, ydAmount: bigint];
  export interface OutputObject {
    instructor: string;
    ydAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YdSwappedToEthEvent {
  export type InputTuple = [
    instructor: AddressLike,
    ydAmount: BigNumberish,
    ethAmount: BigNumberish
  ];
  export type OutputTuple = [
    instructor: string,
    ydAmount: bigint,
    ethAmount: bigint
  ];
  export interface OutputObject {
    instructor: string;
    ydAmount: bigint;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldProcessedEvent {
  export type InputTuple = [
    instructor: AddressLike,
    totalYd: BigNumberish,
    totalUsdt: BigNumberish
  ];
  export type OutputTuple = [
    instructor: string,
    totalYd: bigint,
    totalUsdt: bigint
  ];
  export interface OutputObject {
    instructor: string;
    totalYd: bigint;
    totalUsdt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InstructorYieldManager extends BaseContract {
  connect(runner?: ContractRunner | null): InstructorYieldManager;
  waitForDeployment(): Promise<this>;

  interface: InstructorYieldManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aavePool: TypedContractMethod<[], [string], "view">;

  activeInstructors: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  depositAndInvest: TypedContractMethod<
    [ydAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveInstructors: TypedContractMethod<[], [string[]], "view">;

  getInstructorAaveData: TypedContractMethod<
    [instructor: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        healthFactor: bigint;
      }
    ],
    "view"
  >;

  getInstructorYield: TypedContractMethod<
    [instructor: AddressLike],
    [InstructorYieldManager.InstructorYieldStructOutput],
    "view"
  >;

  instructorYields: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        instructor: string;
        totalYdDeposited: bigint;
        totalUsdtSupplied: bigint;
        lastUpdateTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAavePool: TypedContractMethod<
    [_newPool: AddressLike],
    [void],
    "nonpayable"
  >;

  setUniswapRouter: TypedContractMethod<
    [_newRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapRouter: TypedContractMethod<[], [string], "view">;

  usdtToken: TypedContractMethod<[], [string], "view">;

  ydToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeInstructors"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "depositAndInvest"
  ): TypedContractMethod<[ydAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveInstructors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getInstructorAaveData"
  ): TypedContractMethod<
    [instructor: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        healthFactor: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInstructorYield"
  ): TypedContractMethod<
    [instructor: AddressLike],
    [InstructorYieldManager.InstructorYieldStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "instructorYields"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        instructor: string;
        totalYdDeposited: bigint;
        totalUsdtSupplied: bigint;
        lastUpdateTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAavePool"
  ): TypedContractMethod<[_newPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUniswapRouter"
  ): TypedContractMethod<[_newRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ydToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EthSwappedToUsdt"
  ): TypedContractEvent<
    EthSwappedToUsdtEvent.InputTuple,
    EthSwappedToUsdtEvent.OutputTuple,
    EthSwappedToUsdtEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UsdtSuppliedToAave"
  ): TypedContractEvent<
    UsdtSuppliedToAaveEvent.InputTuple,
    UsdtSuppliedToAaveEvent.OutputTuple,
    UsdtSuppliedToAaveEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawnFromAave"
  ): TypedContractEvent<
    WithdrawnFromAaveEvent.InputTuple,
    WithdrawnFromAaveEvent.OutputTuple,
    WithdrawnFromAaveEvent.OutputObject
  >;
  getEvent(
    key: "YdDeposited"
  ): TypedContractEvent<
    YdDepositedEvent.InputTuple,
    YdDepositedEvent.OutputTuple,
    YdDepositedEvent.OutputObject
  >;
  getEvent(
    key: "YdSwappedToEth"
  ): TypedContractEvent<
    YdSwappedToEthEvent.InputTuple,
    YdSwappedToEthEvent.OutputTuple,
    YdSwappedToEthEvent.OutputObject
  >;
  getEvent(
    key: "YieldProcessed"
  ): TypedContractEvent<
    YieldProcessedEvent.InputTuple,
    YieldProcessedEvent.OutputTuple,
    YieldProcessedEvent.OutputObject
  >;

  filters: {
    "EthSwappedToUsdt(address,uint256,uint256)": TypedContractEvent<
      EthSwappedToUsdtEvent.InputTuple,
      EthSwappedToUsdtEvent.OutputTuple,
      EthSwappedToUsdtEvent.OutputObject
    >;
    EthSwappedToUsdt: TypedContractEvent<
      EthSwappedToUsdtEvent.InputTuple,
      EthSwappedToUsdtEvent.OutputTuple,
      EthSwappedToUsdtEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UsdtSuppliedToAave(address,uint256)": TypedContractEvent<
      UsdtSuppliedToAaveEvent.InputTuple,
      UsdtSuppliedToAaveEvent.OutputTuple,
      UsdtSuppliedToAaveEvent.OutputObject
    >;
    UsdtSuppliedToAave: TypedContractEvent<
      UsdtSuppliedToAaveEvent.InputTuple,
      UsdtSuppliedToAaveEvent.OutputTuple,
      UsdtSuppliedToAaveEvent.OutputObject
    >;

    "WithdrawnFromAave(address,uint256)": TypedContractEvent<
      WithdrawnFromAaveEvent.InputTuple,
      WithdrawnFromAaveEvent.OutputTuple,
      WithdrawnFromAaveEvent.OutputObject
    >;
    WithdrawnFromAave: TypedContractEvent<
      WithdrawnFromAaveEvent.InputTuple,
      WithdrawnFromAaveEvent.OutputTuple,
      WithdrawnFromAaveEvent.OutputObject
    >;

    "YdDeposited(address,uint256)": TypedContractEvent<
      YdDepositedEvent.InputTuple,
      YdDepositedEvent.OutputTuple,
      YdDepositedEvent.OutputObject
    >;
    YdDeposited: TypedContractEvent<
      YdDepositedEvent.InputTuple,
      YdDepositedEvent.OutputTuple,
      YdDepositedEvent.OutputObject
    >;

    "YdSwappedToEth(address,uint256,uint256)": TypedContractEvent<
      YdSwappedToEthEvent.InputTuple,
      YdSwappedToEthEvent.OutputTuple,
      YdSwappedToEthEvent.OutputObject
    >;
    YdSwappedToEth: TypedContractEvent<
      YdSwappedToEthEvent.InputTuple,
      YdSwappedToEthEvent.OutputTuple,
      YdSwappedToEthEvent.OutputObject
    >;

    "YieldProcessed(address,uint256,uint256)": TypedContractEvent<
      YieldProcessedEvent.InputTuple,
      YieldProcessedEvent.OutputTuple,
      YieldProcessedEvent.OutputObject
    >;
    YieldProcessed: TypedContractEvent<
      YieldProcessedEvent.InputTuple,
      YieldProcessedEvent.OutputTuple,
      YieldProcessedEvent.OutputObject
    >;
  };
}
