/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace UserProfile {
  export type ProfileStruct = {
    name: string;
    createdAt: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type ProfileStructOutput = [
    name: string,
    createdAt: bigint,
    lastUpdated: bigint
  ] & { name: string; createdAt: bigint; lastUpdated: bigint };
}

export declare namespace ICoursePurchase {
  export type PurchaseStruct = {
    courseId: BigNumberish;
    student: AddressLike;
    paidAmount: BigNumberish;
    purchaseTime: BigNumberish;
    isValid: boolean;
  };

  export type PurchaseStructOutput = [
    courseId: bigint,
    student: string,
    paidAmount: bigint,
    purchaseTime: bigint,
    isValid: boolean
  ] & {
    courseId: bigint;
    student: string;
    paidAmount: bigint;
    purchaseTime: bigint;
    isValid: boolean;
  };
}

export interface UserProfileInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "coursePurchase"
      | "eip712Domain"
      | "getDomainSeparator"
      | "getNonce"
      | "getProfile"
      | "getPurchasedCourses"
      | "getPurchasedCoursesWithSignature"
      | "hasPurchasedCourse"
      | "nonces"
      | "profiles"
      | "updateName"
      | "updateNameWithSignature"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoursesQueried"
      | "EIP712DomainChanged"
      | "ProfileUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "coursePurchase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPurchasedCourses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPurchasedCoursesWithSignature",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchasedCourse",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "updateName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateNameWithSignature",
    values: [AddressLike, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "coursePurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPurchasedCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPurchasedCoursesWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchasedCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateNameWithSignature",
    data: BytesLike
  ): Result;
}

export namespace CoursesQueriedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    newName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, newName: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    newName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UserProfile extends BaseContract {
  connect(runner?: ContractRunner | null): UserProfile;
  waitForDeployment(): Promise<this>;

  interface: UserProfileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  coursePurchase: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getDomainSeparator: TypedContractMethod<[], [string], "view">;

  getNonce: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getProfile: TypedContractMethod<
    [user: AddressLike],
    [UserProfile.ProfileStructOutput],
    "view"
  >;

  getPurchasedCourses: TypedContractMethod<
    [user: AddressLike],
    [ICoursePurchase.PurchaseStructOutput[]],
    "view"
  >;

  getPurchasedCoursesWithSignature: TypedContractMethod<
    [user: AddressLike, timestamp: BigNumberish, signature: BytesLike],
    [ICoursePurchase.PurchaseStructOutput[]],
    "view"
  >;

  hasPurchasedCourse: TypedContractMethod<
    [user: AddressLike, courseId: BigNumberish],
    [boolean],
    "view"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        name: string;
        createdAt: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  updateName: TypedContractMethod<[newName: string], [void], "nonpayable">;

  updateNameWithSignature: TypedContractMethod<
    [user: AddressLike, newName: string, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "coursePurchase"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDomainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [user: AddressLike],
    [UserProfile.ProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPurchasedCourses"
  ): TypedContractMethod<
    [user: AddressLike],
    [ICoursePurchase.PurchaseStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPurchasedCoursesWithSignature"
  ): TypedContractMethod<
    [user: AddressLike, timestamp: BigNumberish, signature: BytesLike],
    [ICoursePurchase.PurchaseStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchasedCourse"
  ): TypedContractMethod<
    [user: AddressLike, courseId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        name: string;
        createdAt: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateName"
  ): TypedContractMethod<[newName: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateNameWithSignature"
  ): TypedContractMethod<
    [user: AddressLike, newName: string, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CoursesQueried"
  ): TypedContractEvent<
    CoursesQueriedEvent.InputTuple,
    CoursesQueriedEvent.OutputTuple,
    CoursesQueriedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;

  filters: {
    "CoursesQueried(address,uint256)": TypedContractEvent<
      CoursesQueriedEvent.InputTuple,
      CoursesQueriedEvent.OutputTuple,
      CoursesQueriedEvent.OutputObject
    >;
    CoursesQueried: TypedContractEvent<
      CoursesQueriedEvent.InputTuple,
      CoursesQueriedEvent.OutputTuple,
      CoursesQueriedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "ProfileUpdated(address,string,uint256)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
  };
}
