/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface YDFaucetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canClaim"
      | "claim"
      | "cooldownTime"
      | "faucetAmount"
      | "fundFaucet"
      | "getFaucetBalance"
      | "lastClaim"
      | "nextClaimTime"
      | "owner"
      | "renounceOwnership"
      | "setCooldownTime"
      | "setFaucetAmount"
      | "totalClaimed"
      | "totalUsers"
      | "transferOwnership"
      | "withdrawFaucet"
      | "ydToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "CooldownTimeUpdated"
      | "FaucetAmountUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cooldownTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "faucetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundFaucet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFaucetBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextClaimTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldownTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFaucetAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFaucet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ydToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "canClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cooldownTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundFaucet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFaucetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextClaimTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCooldownTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFaucetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFaucet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ydToken", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CooldownTimeUpdatedEvent {
  export type InputTuple = [newTime: BigNumberish];
  export type OutputTuple = [newTime: bigint];
  export interface OutputObject {
    newTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetAmountUpdatedEvent {
  export type InputTuple = [newAmount: BigNumberish];
  export type OutputTuple = [newAmount: bigint];
  export interface OutputObject {
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YDFaucet extends BaseContract {
  connect(runner?: ContractRunner | null): YDFaucet;
  waitForDeployment(): Promise<this>;

  interface: YDFaucetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canClaim: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  cooldownTime: TypedContractMethod<[], [bigint], "view">;

  faucetAmount: TypedContractMethod<[], [bigint], "view">;

  fundFaucet: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFaucetBalance: TypedContractMethod<[], [bigint], "view">;

  lastClaim: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  nextClaimTime: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCooldownTime: TypedContractMethod<
    [newTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFaucetAmount: TypedContractMethod<
    [newAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalClaimed: TypedContractMethod<[], [bigint], "view">;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFaucet: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ydToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canClaim"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cooldownTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucetAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundFaucet"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getFaucetBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastClaim"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextClaimTime"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCooldownTime"
  ): TypedContractMethod<[newTime: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFaucetAmount"
  ): TypedContractMethod<[newAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalClaimed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFaucet"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ydToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CooldownTimeUpdated"
  ): TypedContractEvent<
    CooldownTimeUpdatedEvent.InputTuple,
    CooldownTimeUpdatedEvent.OutputTuple,
    CooldownTimeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FaucetAmountUpdated"
  ): TypedContractEvent<
    FaucetAmountUpdatedEvent.InputTuple,
    FaucetAmountUpdatedEvent.OutputTuple,
    FaucetAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "Claimed(address,uint256,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "CooldownTimeUpdated(uint256)": TypedContractEvent<
      CooldownTimeUpdatedEvent.InputTuple,
      CooldownTimeUpdatedEvent.OutputTuple,
      CooldownTimeUpdatedEvent.OutputObject
    >;
    CooldownTimeUpdated: TypedContractEvent<
      CooldownTimeUpdatedEvent.InputTuple,
      CooldownTimeUpdatedEvent.OutputTuple,
      CooldownTimeUpdatedEvent.OutputObject
    >;

    "FaucetAmountUpdated(uint256)": TypedContractEvent<
      FaucetAmountUpdatedEvent.InputTuple,
      FaucetAmountUpdatedEvent.OutputTuple,
      FaucetAmountUpdatedEvent.OutputObject
    >;
    FaucetAmountUpdated: TypedContractEvent<
      FaucetAmountUpdatedEvent.InputTuple,
      FaucetAmountUpdatedEvent.OutputTuple,
      FaucetAmountUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
