/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace YDStakingSafe {
  export type StakeStruct = {
    stakeId: BigNumberish;
    user: AddressLike;
    ethAmount: BigNumberish;
    ydAmount: BigNumberish;
    tier: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    claimedReward: BigNumberish;
    isActive: boolean;
  };

  export type StakeStructOutput = [
    stakeId: bigint,
    user: string,
    ethAmount: bigint,
    ydAmount: bigint,
    tier: bigint,
    startTime: bigint,
    endTime: bigint,
    claimedReward: bigint,
    isActive: boolean
  ] & {
    stakeId: bigint;
    user: string;
    ethAmount: bigint;
    ydAmount: bigint;
    tier: bigint;
    startTime: bigint;
    endTime: bigint;
    claimedReward: bigint;
    isActive: boolean;
  };

  export type StakingTierStruct = {
    minAmount: BigNumberish;
    ydReward: BigNumberish;
    lockPeriod: BigNumberish;
    apy: BigNumberish;
    isActive: boolean;
  };

  export type StakingTierStructOutput = [
    minAmount: bigint,
    ydReward: bigint,
    lockPeriod: bigint,
    apy: bigint,
    isActive: boolean
  ] & {
    minAmount: bigint;
    ydReward: bigint;
    lockPeriod: bigint;
    apy: bigint;
    isActive: boolean;
  };
}

export interface YDStakingSafeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeStakeIds"
      | "calculateReward"
      | "claimReward"
      | "emergencyAdmin"
      | "emergencyWithdraw"
      | "emergencyWithdrawAll"
      | "fundYD"
      | "getActiveStakeIds"
      | "getActiveStakes"
      | "getAllTiers"
      | "getContractBalance"
      | "getUserStakes"
      | "owner"
      | "pause"
      | "paused"
      | "platformRevenue"
      | "renounceOwnership"
      | "setEmergencyAdmin"
      | "stake"
      | "stakeIdToIndex"
      | "stakes"
      | "stakingTiers"
      | "totalStakes"
      | "totalTiers"
      | "totalUserStaked"
      | "transferOwnership"
      | "unpause"
      | "unstake"
      | "unstakeEarly"
      | "userStakes"
      | "userWithdrawable"
      | "withdrawAllPlatformRevenue"
      | "withdrawExcessYD"
      | "withdrawPlatformRevenue"
      | "ydToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyAdminChanged"
      | "EmergencyWithdraw"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformRevenueWithdrawn"
      | "Staked"
      | "Unpaused"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeStakeIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundYD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveStakeIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTiers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakeIdToIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTiers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUserStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeEarly",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStakes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userWithdrawable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllPlatformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawExcessYD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformRevenue",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ydToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "activeStakeIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundYD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveStakeIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeIdToIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakingTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalTiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalUserStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeEarly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userStakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userWithdrawable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllPlatformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawExcessYD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ydToken", data: BytesLike): Result;
}

export namespace EmergencyAdminChangedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    stakeId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    operator: AddressLike
  ];
  export type OutputTuple = [
    stakeId: bigint,
    user: string,
    amount: bigint,
    operator: string
  ];
  export interface OutputObject {
    stakeId: bigint;
    user: string;
    amount: bigint;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformRevenueWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    stakeId: BigNumberish,
    user: AddressLike,
    ethAmount: BigNumberish,
    ydAmount: BigNumberish
  ];
  export type OutputTuple = [
    stakeId: bigint,
    user: string,
    ethAmount: bigint,
    ydAmount: bigint
  ];
  export interface OutputObject {
    stakeId: bigint;
    user: string;
    ethAmount: bigint;
    ydAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    stakeId: BigNumberish,
    user: AddressLike,
    ethAmount: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    stakeId: bigint,
    user: string,
    ethAmount: bigint,
    reward: bigint
  ];
  export interface OutputObject {
    stakeId: bigint;
    user: string;
    ethAmount: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YDStakingSafe extends BaseContract {
  connect(runner?: ContractRunner | null): YDStakingSafe;
  waitForDeployment(): Promise<this>;

  interface: YDStakingSafeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeStakeIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  calculateReward: TypedContractMethod<
    [stakeId: BigNumberish],
    [bigint],
    "view"
  >;

  claimReward: TypedContractMethod<
    [stakeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyAdmin: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<
    [stakeId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawAll: TypedContractMethod<[], [void], "nonpayable">;

  fundYD: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getActiveStakeIds: TypedContractMethod<[], [bigint[]], "view">;

  getActiveStakes: TypedContractMethod<
    [user: AddressLike],
    [YDStakingSafe.StakeStructOutput[]],
    "view"
  >;

  getAllTiers: TypedContractMethod<
    [],
    [YDStakingSafe.StakingTierStructOutput[]],
    "view"
  >;

  getContractBalance: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalBalance: bigint;
        userStaked: bigint;
        platformRev: bigint;
        available: bigint;
      }
    ],
    "view"
  >;

  getUserStakes: TypedContractMethod<
    [user: AddressLike],
    [YDStakingSafe.StakeStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformRevenue: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEmergencyAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[tier: BigNumberish], [void], "payable">;

  stakeIdToIndex: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  stakes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        stakeId: bigint;
        user: string;
        ethAmount: bigint;
        ydAmount: bigint;
        tier: bigint;
        startTime: bigint;
        endTime: bigint;
        claimedReward: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  stakingTiers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        minAmount: bigint;
        ydReward: bigint;
        lockPeriod: bigint;
        apy: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  totalStakes: TypedContractMethod<[], [bigint], "view">;

  totalTiers: TypedContractMethod<[], [bigint], "view">;

  totalUserStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unstake: TypedContractMethod<[stakeId: BigNumberish], [void], "nonpayable">;

  unstakeEarly: TypedContractMethod<
    [stakeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userStakes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        stakeId: bigint;
        user: string;
        ethAmount: bigint;
        ydAmount: bigint;
        tier: bigint;
        startTime: bigint;
        endTime: bigint;
        claimedReward: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  userWithdrawable: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawAllPlatformRevenue: TypedContractMethod<[], [void], "nonpayable">;

  withdrawExcessYD: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawPlatformRevenue: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ydToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeStakeIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateReward"
  ): TypedContractMethod<[stakeId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[stakeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [stakeId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdrawAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundYD"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveStakeIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getActiveStakes"
  ): TypedContractMethod<
    [user: AddressLike],
    [YDStakingSafe.StakeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllTiers"
  ): TypedContractMethod<[], [YDStakingSafe.StakingTierStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalBalance: bigint;
        userStaked: bigint;
        platformRev: bigint;
        available: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStakes"
  ): TypedContractMethod<
    [user: AddressLike],
    [YDStakingSafe.StakeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmergencyAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[tier: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "stakeIdToIndex"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        stakeId: bigint;
        user: string;
        ethAmount: bigint;
        ydAmount: bigint;
        tier: bigint;
        startTime: bigint;
        endTime: bigint;
        claimedReward: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakingTiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        minAmount: bigint;
        ydReward: bigint;
        lockPeriod: bigint;
        apy: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalStakes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTiers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUserStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[stakeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeEarly"
  ): TypedContractMethod<[stakeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userStakes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        stakeId: bigint;
        user: string;
        ethAmount: bigint;
        ydAmount: bigint;
        tier: bigint;
        startTime: bigint;
        endTime: bigint;
        claimedReward: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userWithdrawable"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawAllPlatformRevenue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawExcessYD"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformRevenue"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ydToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EmergencyAdminChanged"
  ): TypedContractEvent<
    EmergencyAdminChangedEvent.InputTuple,
    EmergencyAdminChangedEvent.OutputTuple,
    EmergencyAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformRevenueWithdrawn"
  ): TypedContractEvent<
    PlatformRevenueWithdrawnEvent.InputTuple,
    PlatformRevenueWithdrawnEvent.OutputTuple,
    PlatformRevenueWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "EmergencyAdminChanged(address,address)": TypedContractEvent<
      EmergencyAdminChangedEvent.InputTuple,
      EmergencyAdminChangedEvent.OutputTuple,
      EmergencyAdminChangedEvent.OutputObject
    >;
    EmergencyAdminChanged: TypedContractEvent<
      EmergencyAdminChangedEvent.InputTuple,
      EmergencyAdminChangedEvent.OutputTuple,
      EmergencyAdminChangedEvent.OutputObject
    >;

    "EmergencyWithdraw(uint256,address,uint256,address)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformRevenueWithdrawn(address,uint256)": TypedContractEvent<
      PlatformRevenueWithdrawnEvent.InputTuple,
      PlatformRevenueWithdrawnEvent.OutputTuple,
      PlatformRevenueWithdrawnEvent.OutputObject
    >;
    PlatformRevenueWithdrawn: TypedContractEvent<
      PlatformRevenueWithdrawnEvent.InputTuple,
      PlatformRevenueWithdrawnEvent.OutputTuple,
      PlatformRevenueWithdrawnEvent.OutputObject
    >;

    "Staked(uint256,address,uint256,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Unstaked(uint256,address,uint256,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
